runmode: debug
addr: :6663
mysql:
  username: user
  password: '****'
  databasename: tcp(localhost:3306)/dbname
  parameter: parseTime=true
redis:
  password:
  url: 127.0.0.1:6379
github:
  client:
    id: '****'
    secret: '****'
jwt:
  token-key: '****'
  token-exp-duration: 72h
tencentyun:
  secret-id: '****'
  secret-key: '****'
  app-id: 12345
  avatar-bucket:
    name: avatar-1255545382
    region: ap-shanghai